apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ template "powerdns.fullname" . }}-ssl-certs"
  labels:
{{ include "powerdns.labels" . | indent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-csi
  resources:
    requests:
      storage: 10Mi
